// Code generated by otiogen. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the OpenTimelineIO project

package jsonenc

import (
	"github.com/mrjoshuak/gotio/opentime"
	"reflect"
)

// encodeRationalTime encodes a RationalTime to JSON.
func encodeRationalTime(enc *Encoder, v any) error {
	t := v.(opentime.RationalTime)
	enc.BeginObject()
	enc.WriteStringField("OTIO_SCHEMA", "RationalTime.1")
	enc.WriteFloat64Field("value", t.Value())
	enc.WriteFloat64Field("rate", t.Rate())
	enc.EndObject()
	return nil
}

func init() {
	Register(TypeInfo{
		SchemaName:    "RationalTime",
		SchemaVersion: 1,
		GoType:        reflect.TypeOf(opentime.RationalTime{}),
		Encode:        encodeRationalTime,
	})
}

// encodeTimeRange encodes a TimeRange to JSON.
func encodeTimeRange(enc *Encoder, v any) error {
	t := v.(opentime.TimeRange)
	enc.BeginObject()
	enc.WriteStringField("OTIO_SCHEMA", "TimeRange.1")
	enc.WriteKey("start_time")
	if err := encodeRationalTime(enc, t.StartTime()); err != nil {
		return err
	}
	enc.WriteKey("duration")
	if err := encodeRationalTime(enc, t.Duration()); err != nil {
		return err
	}
	enc.EndObject()
	return nil
}

func init() {
	Register(TypeInfo{
		SchemaName:    "TimeRange",
		SchemaVersion: 1,
		GoType:        reflect.TypeOf(opentime.TimeRange{}),
		Encode:        encodeTimeRange,
	})
}

// encodeTimeTransform encodes a TimeTransform to JSON.
func encodeTimeTransform(enc *Encoder, v any) error {
	t := v.(opentime.TimeTransform)
	enc.BeginObject()
	enc.WriteStringField("OTIO_SCHEMA", "TimeTransform.1")
	enc.WriteKey("offset")
	if err := encodeRationalTime(enc, t.Offset()); err != nil {
		return err
	}
	enc.WriteFloat64Field("scale", t.Scale())
	enc.WriteFloat64Field("rate", t.Rate())
	enc.EndObject()
	return nil
}

func init() {
	Register(TypeInfo{
		SchemaName:    "TimeTransform",
		SchemaVersion: 1,
		GoType:        reflect.TypeOf(opentime.TimeTransform{}),
		Encode:        encodeTimeTransform,
	})
}
